# Generated by Django 5.2.14 on 2026-05-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('full_name_without_titles', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title_before', models.CharField(blank=True, max_length=255, null=True)),
                ('title_after', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount_in_default_currency', models.IntegerField()),
                ('trading_profit', models.IntegerField()),
                ('status', models.CharField(choices=[('B_ACTIVE', 'Active'), ('E_WIN', 'Win'), ('F_LOST', 'Lost')], max_length=20)),
                ('exchange_rate', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_business_cases', to='r_core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
